
export const SCAN_METRC_TAG = 'SCAN_METRC_TAG';
export const SCAN_METRC_TAG_SUCCESS = 'SCAN_METRC_TAG_SUCCESS';
export const SCAN_METRC_TAG_FAILURE = 'SCAN_METRC_TAG_FAILURE';

export const RESET_METRC_ORDER_SCANS = 'RESET_METRC_ORDER_SCANS';
export const RESET_METRC_ORDER_SCANS_SUCCESS = 'RESET_METRC_ORDER_SCANS_SUCCESS';
export const RESET_METRC_ORDER_SCANS_FAILURE = 'RESET_METRC_ORDER_SCANS_FAILURE';

export const RESET_METRC_ORDER_DETAIL_SCANS = 'RESET_METRC_ORDER_DETAIL_SCANS';
export const RESET_METRC_ORDER_DETAIL_SCANS_SUCCESS = 'RESET_METRC_ORDER_DETAIL_SCANS_SUCCESS';
export const RESET_METRC_ORDER_DETAIL_SCANS_FAILURE = 'RESET_METRC_ORDER_DETAIL_SCANS_FAILURE';